export default defineEventHandler(async () => {
  // Data compiled from GitHub search for Flipper Zero alternatives
  const alternatives = [
    {
      name: 'Willy Firmware V2',
      owner: 'h-RAT',
      description: 'Willy Firmware is an alternative to Flipper Zero. | Board: ESP32 T-Display-S3 - Module: CC1101 - Display: Touchscreen - Compatible Flipper Zero file.',
      stars: 563,
      language: 'HTML',
      url: 'https://github.com/h-RAT/Willy_Firmware_V2_ESP32_Flipper_Zero_Alternative',
      topics: ['cc1101', 'esp32', 'flipper-zero', 'flipperzero', 'hack-rf', 'hack-rf-sdr', 'kaiju'],
    },
    {
      name: 'EvilCrowRF Custom Firmware',
      owner: 'h-RAT',
      description: 'This firmware is an alternative to the EvilCrowRF default firmware. Module: CC1101 - Compatible Flipper Zero file.',
      stars: 516,
      language: 'HTML',
      url: 'https://github.com/h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero',
      topics: ['cc1101', 'esp32', 'flipper-zero', 'hack-rf'],
    },
    {
      name: 'Orca One',
      owner: 'OceanTroop',
      description: 'A collection of alternatives for running Flipper Zero functions on more affordable devices such as M5Stack, Liligo and ESP32 in general.',
      stars: 357,
      language: 'C++',
      url: 'https://github.com/OceanTroop/orca-one',
      topics: [],
    },
    {
      name: 'HIZMOS',
      owner: 'Hiktron',
      description: '⚡ HIZMOS — An open-source, powerful alternative to Flipper Zero. Built on ESP32-S3, designed for pentesting, RF hacking, cybersecurity, and STEM education. Affordable, accessible, and packed with unique hardware features.',
      stars: 29,
      language: 'C',
      url: 'https://github.com/Hiktron/Hizmos',
      topics: [],
    },
    {
      name: 'Snowflake',
      owner: 'FutureJames',
      description: 'DIY alternative to the very cool Flipper Zero project',
      stars: 20,
      language: 'Python',
      url: 'https://github.com/FutureJames/snowflake',
      topics: [],
    },
    {
      name: 'Flipper Zero Input',
      owner: 'jamisonderek',
      description: 'Alternative input for the Flipper Zero',
      stars: 16,
      language: 'C',
      url: 'https://github.com/jamisonderek/flipper-zero-input',
      topics: [],
    },
    {
      name: 'Willy (ESP32-S3)',
      owner: 'mtojek',
      description: 'Flipper Zero alternative built for ESP32-S3',
      stars: 13,
      language: 'C++',
      url: 'https://github.com/mtojek/willy',
      topics: [],
    },
    {
      name: 'DIY Flipper DevBoard',
      owner: 'Master-YCK',
      description: 'This project offers a budget-friendly alternative to the official ESP32 WiFi board for the Flipper Zero, giving tech enthusiasts a chance to save money while gaining practical experience in assembling, configuring, and customizing their own hardware solution.',
      stars: 10,
      language: null,
      url: 'https://github.com/Master-YCK/DIY-Flipper-DevBoard',
      topics: ['begginer-friendly', 'diy-electronics', 'esp32', 'flipperzero'],
    },
    {
      name: 'FlipperZero ESP WROOM32',
      owner: 'snsational',
      description: 'WiFi Module for the Flipper Zero as an alternative to the official WiFi Devboard by Flipper Devices',
      stars: 9,
      language: null,
      url: 'https://github.com/snsational/flipperzero-espwroom32',
      topics: [],
    },
    {
      name: 'M5Stack',
      owner: 'M5Shark',
      description: 'Open-source tools and firmware for M5StickC, CC1101, and M5Stack devices. Build your own Flipper Zero alternative with RF, IR, and BadUSB features. Visit https://m5shark.com to get the hardware.',
      stars: 6,
      language: null,
      url: 'https://github.com/M5Shark/M5Stack',
      topics: [],
    },
    {
      name: 'DIY Flipper Zero',
      owner: 'Muhib-Mehdi',
      description: 'A cheaper alternative to flipper zero that still has 50% of the functionality',
      stars: 3,
      language: null,
      url: 'https://github.com/Muhib-Mehdi/DIY-flipper-zero-',
      topics: [],
    },
    {
      name: 'NiA-FBT26',
      owner: 'NaTo1000',
      description: 'Advanced Flipper Zero Development Suite - qFlipper alternative with FAP/Firmware builders, Arduino/ESP32 support, integrated terminal, and GitHub integration',
      stars: 1,
      language: 'Shell',
      url: 'https://github.com/NaTo1000/NiA-FBT26',
      topics: [],
    },
    {
      name: 'Gemini-Hizmos',
      owner: 'look4green',
      description: 'An open-source, powerful alternative to Flipper Zero. Built on ESP32-S3, designed for pentesting, RF hacking, cybersecurity, and STEM education. Affordable, accessible, and packed with unique hardware features.',
      stars: 1,
      language: 'C',
      url: 'https://github.com/look4green/Gemini-Hizmos',
      topics: [],
    },
    {
      name: 'Flipper-zero-alternative',
      owner: 'cikolllooid',
      description: '',
      stars: 0,
      language: 'C',
      url: 'https://github.com/cikolllooid/Flipper-zero-alternative',
      topics: [],
    },
    {
      name: 'DIY-Flipper',
      owner: 'FlipperZX',
      description: 'A DIY alternative to the flipper zero',
      stars: 0,
      language: null,
      url: 'https://github.com/FlipperZX/DIY-Flipper',
      topics: [],
    },
    {
      name: 'shark1',
      owner: 'h4cker891',
      description: 'The best flipper zero alternative, with even more capabilities.',
      stars: 0,
      language: null,
      url: 'https://github.com/h4cker891/shark1',
      topics: [],
    },
    {
      name: 'cosmob1',
      owner: 'gabrielesuardi',
      description: 'cosmo b1 is the brand new alternative to flipper zero, chepaer, and with a new method of interface',
      stars: 0,
      language: 'HTML',
      url: 'https://github.com/gabrielesuardi/cosmob1',
      topics: [],
    },
    {
      name: 'starlog',
      owner: 'ayberkarslan',
      description: 'An ESP32 based DIY pocket multi-tool for pentesting and fun. Features IR Signal Cloning,Wi-Fi Deauth, Beacon Spam and Retro Games. Open-source Flipper Zero alternative.',
      stars: 0,
      language: 'C++',
      url: 'https://github.com/ayberkarslan/starlog',
      topics: ['cpp', 'esp32', 'flipper-zero', 'pentest-tool', 'state-machine', 'wifi-beaconpacket', 'wifi-deauther'],
    },
  ]

  return {
    total: alternatives.length,
    alternatives: alternatives.sort((a, b) => b.stars - a.stars),
  }
})
